repellency:
  method: safe_denoiser
  n_embed: 8
  neg_start: 1000
  neg_end: 800
  params:
    scale: 0.03
    proj_ref_path : "caches/sd_sgf/multi_7c_all/repellency_proj_ref.pt"
    cache_proj_ref : False

data:
  name: nudity
  root: datasets/nudity
  class_info : multi_7c_all

mean_processor:
  dynamic_threshold: False
  clip_denoised: True
