#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Concept Pack Loader — shared utility for multi-concept erasing.

Loads concept packs from disk so that any generate_v*.py can consume them.
Each concept pack contains metadata, family definitions, keywords, prompts,
and optionally precomputed .pt tensors (concept_directions, clip_patch_tokens,
contrastive_embeddings).

Concept pack directory layout:
    concept_packs/<concept>/
      metadata.json
      families.json
      target_prompts.txt
      anchor_prompts.txt
      target_keywords_primary.txt
      target_keywords_secondary.txt
      anchor_keywords.txt
      concept_directions.pt       (optional, generated by prep)
      clip_patch_tokens.pt        (optional, generated by prep)
      contrastive_embeddings.pt   (optional, generated by prep)

Usage:
    from concept_pack_loader import load_concept_pack, load_multiple_packs

    pack = load_concept_pack("concept_packs/violence")
    packs = load_multiple_packs(["concept_packs/violence", "concept_packs/sexual"])
"""

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import torch


# =========================================================================
# Data classes
# =========================================================================
@dataclass
class ConceptFamily:
    """One family within a concept (e.g., weapon_threat within violence)."""
    name: str
    target_words: List[str]
    anchor_words: List[str]
    mapping_strength: str  # strong / medium / weak
    pilot: bool


@dataclass
class ConceptPack:
    """One loaded concept (e.g., violence)."""
    name: str
    cas_threshold: float
    probe_source: str          # text / image / both
    guide_mode: str            # dag_adaptive / hybrid
    families: List[ConceptFamily]
    target_keywords_primary: List[str]
    target_keywords_secondary: List[str]
    anchor_keywords: List[str]
    target_prompts: List[str]
    anchor_prompts: List[str]
    concept_directions: Optional[dict] = None       # from concept_directions.pt
    clip_embeddings: Optional[Any] = None           # from clip_patch_tokens.pt
    contrastive_embeddings: Optional[dict] = None   # from contrastive_embeddings.pt
    metadata: Dict[str, Any] | None = None
    pack_dir: str = ""

    @property
    def target_concepts(self) -> List[str]:
        if self.target_keywords_primary:
            return self.target_keywords_primary
        if self.target_prompts:
            return self.target_prompts
        return [self.name]

    @property
    def anchor_concepts(self) -> List[str]:
        if self.anchor_keywords:
            return self.anchor_keywords
        if self.anchor_prompts:
            return self.anchor_prompts
        return [f"safe {self.name}"]

    @property
    def target_words(self) -> List[str]:
        return _dedupe_preserve_order(
            self.target_keywords_primary + self.target_keywords_secondary
        )

    def get(self, key: str, default: Any = None) -> Any:
        mapping = {
            "concept": self.name,
            "cas_threshold": self.cas_threshold,
            "probe_source": self.probe_source,
            "guide_mode": self.guide_mode,
            "target_concepts": self.target_concepts,
            "anchor_concepts": self.anchor_concepts,
            "target_words": self.target_words,
            "anchor_words": self.anchor_keywords,
            "concept_directions": self.concept_directions,
            "clip_embeddings": self.clip_embeddings,
            "contrastive_embeddings": self.contrastive_embeddings,
            "pack_dir": self.pack_dir,
        }

        if self.concept_directions:
            for nested_key in ("target_directions", "anchor_directions", "target_global", "anchor_global"):
                if nested_key in self.concept_directions:
                    mapping[nested_key] = self.concept_directions[nested_key]

        if self.metadata:
            if key in self.metadata:
                return self.metadata[key]

        return mapping.get(key, default)

    def __getitem__(self, key: str) -> Any:
        value = self.get(key, None)
        if value is None:
            raise KeyError(key)
        return value

    def __contains__(self, key: str) -> bool:
        return self.get(key, None) is not None


def _dedupe_preserve_order(items: List[str]) -> List[str]:
    seen = set()
    result = []
    for item in items:
        if item not in seen:
            seen.add(item)
            result.append(item)
    return result


# =========================================================================
# File reading helpers
# =========================================================================
def _read_lines(path: Path) -> List[str]:
    """Read a text file and return non-empty stripped lines."""
    if not path.exists():
        return []
    with open(path, "r", encoding="utf-8") as f:
        return [line.strip() for line in f if line.strip()]


def _load_json(path: Path) -> dict:
    """Load a JSON file."""
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def _load_pt(path: Path, device: str = "cpu") -> Optional[dict]:
    """Load a .pt file if it exists, return None otherwise."""
    if not path.exists():
        return None
    return torch.load(path, map_location=device, weights_only=False)


# =========================================================================
# Core loaders
# =========================================================================
def load_concept_pack(pack_dir: str, device: str = "cuda") -> ConceptPack:
    """
    Load a single concept pack from directory.

    Args:
        pack_dir: path to the concept pack directory
        device: device for loading .pt tensors ('cuda' or 'cpu')

    Returns:
        ConceptPack with all available data loaded
    """
    d = Path(pack_dir)
    if not d.is_dir():
        raise FileNotFoundError(f"Concept pack directory not found: {d}")

    # --- Required JSON files ---
    metadata_path = d / "metadata.json"
    families_path = d / "families.json"

    if not metadata_path.exists():
        raise FileNotFoundError(f"metadata.json not found in {d}")
    if not families_path.exists():
        raise FileNotFoundError(f"families.json not found in {d}")

    metadata = _load_json(metadata_path)
    families_data = _load_json(families_path)

    # --- Parse families ---
    families = []
    for fam in families_data.get("families", []):
        families.append(ConceptFamily(
            name=fam["name"],
            target_words=fam.get("target_words", []),
            anchor_words=fam.get("anchor_words", []),
            mapping_strength=fam.get("mapping_strength", "medium"),
            pilot=fam.get("pilot", False),
        ))

    # --- Read keyword / prompt text files ---
    target_kw_primary = _read_lines(d / "target_keywords_primary.txt")
    target_kw_secondary = _read_lines(d / "target_keywords_secondary.txt")
    anchor_kw = _read_lines(d / "anchor_keywords.txt")
    target_prompts = _read_lines(d / "target_prompts.txt")
    anchor_prompts = _read_lines(d / "anchor_prompts.txt")

    # --- Load optional .pt files ---
    concept_dirs = _load_pt(d / "concept_directions.pt", device)
    clip_emb = _load_pt(d / "clip_patch_tokens.pt", device)
    contrastive_emb = _load_pt(d / "contrastive_embeddings.pt", device)

    return ConceptPack(
        name=metadata.get("concept", d.name),
        cas_threshold=metadata.get("cas_threshold", 0.5),
        probe_source=metadata.get("recommended_probe_source", "text"),
        guide_mode=metadata.get("recommended_guide_mode", "dag_adaptive"),
        families=families,
        target_keywords_primary=target_kw_primary,
        target_keywords_secondary=target_kw_secondary,
        anchor_keywords=anchor_kw,
        target_prompts=target_prompts,
        anchor_prompts=anchor_prompts,
        concept_directions=concept_dirs,
        clip_embeddings=clip_emb,
        contrastive_embeddings=contrastive_emb,
        metadata=metadata,
        pack_dir=str(d),
    )


def load_multiple_packs(
    pack_dirs: List[str], device: str = "cuda"
) -> List[ConceptPack]:
    """
    Load multiple concept packs for simultaneous erasing.

    Args:
        pack_dirs: list of paths to concept pack directories
        device: device for loading .pt tensors

    Returns:
        list of ConceptPack objects
    """
    packs = []
    for pd in pack_dirs:
        print(f"Loading concept pack: {pd}")
        packs.append(load_concept_pack(pd, device=device))
    print(f"Loaded {len(packs)} concept packs: "
          f"{[p.name for p in packs]}")
    return packs


# =========================================================================
# Utility functions
# =========================================================================
def get_combined_target_words(
    packs: List[ConceptPack], primary_only: bool = False
) -> List[str]:
    """
    Combine target keywords from all packs (for text probe).

    Args:
        packs: list of loaded ConceptPack objects
        primary_only: if True, only include primary keywords

    Returns:
        deduplicated list of target keywords
    """
    words = []
    for p in packs:
        words.extend(p.target_keywords_primary)
        if not primary_only:
            words.extend(p.target_keywords_secondary)
    return _dedupe_preserve_order(words)


def get_all_target_prompts(pack_dir: str) -> Tuple[List[str], List[str]]:
    """
    Read target_prompts.txt and anchor_prompts.txt from a pack directory.

    Args:
        pack_dir: path to the concept pack directory

    Returns:
        (target_prompts, anchor_prompts) — two lists of prompt strings
    """
    d = Path(pack_dir)
    targets = _read_lines(d / "target_prompts.txt")
    anchors = _read_lines(d / "anchor_prompts.txt")
    return targets, anchors


def get_pilot_families(pack: ConceptPack) -> List[ConceptFamily]:
    """Return only families marked as pilot (for initial experiments)."""
    return [f for f in pack.families if f.pilot]


def get_families_by_strength(
    pack: ConceptPack, strength: str
) -> List[ConceptFamily]:
    """Return families filtered by mapping_strength (strong/medium/weak)."""
    return [f for f in pack.families if f.mapping_strength == strength]
