model_type: time_dependent_vaal
model_args:
  vae:
    image_size: 64
    classifier_use_fp16: False
    classifier_width: 128
    # classifier_depth: 2
    classifier_depth: 1
    classifier_attention_resolutions: "32,16,8"
    classifier_use_scale_shift_norm: True
    classifier_resblock_updown: True
    classifier_pool: "attention"
    # out_channels: 512
    out_channels: 4
    in_channels: 4

  discriminator:
    image_size: 8
    classifier_use_fp16: False
    # classifier_width: 128
    # classifier_depth: 2
    classifier_width: 256
    classifier_depth: 8
    classifier_attention_resolutions: "32,16,8"
    classifier_use_scale_shift_norm: True
    classifier_resblock_updown: True
    classifier_pool: "attention"
    out_channels: 1
    in_channels: 512
