model_type: augmented_discriminator
model_args:
  image_size: 64
  classifier_use_fp16: False
  classifier_width: 128
  classifier_depth: 2
  classifier_attention_resolutions: "32,16,8"
  classifier_use_scale_shift_norm: True
  classifier_resblock_updown: True
  classifier_pool: "attention"
  out_channels: 1
  in_channels: 4
  use_pretrained_layer: False # This is the only difference between the two configurations