model_type: time_dependent_discriminator
model_args:
  image_size: 128
  classifier_use_fp16: False
  classifier_width: 128
  classifier_depth: 2
  classifier_attention_resolutions: "32,16,8"
  classifier_use_scale_shift_norm: True
  classifier_resblock_updown: True
  classifier_pool: "attention"
  out_channels: 11
  in_channels: 4